version: '3.9'
services:
  vpn:
    image: docker.io/qmcgaw/gluetun
    environment:
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      # SERVER_COUNTRIES: ${SERVER_COUNTRIES}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # ports:
    #   - 8000:8000/tcp
    volumes:
      - ./${VPN_SERVICE_PROVIDER}:/gluetun
    networks:
      default: {}
  vpnrotate:
    image: docker.io/alpine/curl
    entrypoint: ["/bin/sh"]
    command:
      - -c
      - |
        while :
        do
          sleep 12
          date
          curl -s http://127.0.0.1:8000/v1/publicip/ip
          echo "Waiting ${VPN_ROTATE_MINUTES} minutes.."
          sleep ${VPN_ROTATE_MINUTES}m
          echo "Restarting VPN connection.."
          curl -s -X PUT -d '{"status":"stopped"}' http://127.0.0.1:8000/v1/openvpn/status
          curl -s -X PUT -d '{"status":"running"}' http://127.0.0.1:8000/v1/openvpn/status
        done
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
  tool:
    image: ${TOOL_IMAGE}
    command: ${TOOL_COMMAND}
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
networks:
  default: {}
